server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: http://localhost:8081