POST http://localhost:8080/api/auth/create
Content-Type: application/json

{
  "username": "john_doesdsss",
  "email": "johsdssss@example.com",
  "password": "securePassword123+!",
  "firstName": "John",
  "lastName": "Doe",
  "bio": "I love Kotlin!",
  "profilePictureUrl": "https://example.com/profile.jpg"
}

###
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "email": "johsds@example.com",
  "password": "securePassword123+!"
}

###
GET http://localhost:8080/api/auth/test-endpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNmNjNGNjOC1hODY1LTRjYWEtOGRiYS1jYjliN2FhY2RiZGQiLCJpc3MiOiJnYXRld2F5IiwiaWF0IjoxNzQyNjYxNjMxLCJwYXlsb2FkIjoiYWZjYTFmZDVhOTc3Yjc4MGUzMWRlOTFhMzJjMTlkMDE1OGQ2MGE2OWJhYWI2MTQxM2U2NTZhZTM5NTRiYmE0ZSIsImV4cCI6MTc0NTI1MzYzMX0.Gbd8F1sntxCDg2armacvvjrQYSqqRz-j6UiSys62-yM
X-JWS-Payload: asdddasd